// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kdRfqwpet3dqNMUqq-sf_0Dd3qbGavE',
    appId: '1:794337546916:web:d8b420acbce0fdde554c31',
    messagingSenderId: '794337546916',
    projectId: 'metro-1f17c',
    authDomain: 'metro-1f17c.firebaseapp.com',
    storageBucket: 'metro-1f17c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOR-7QlMBxl0nbExdL250XxLb3HDdLEk8',
    appId: '1:794337546916:android:412976dc11755957554c31',
    messagingSenderId: '794337546916',
    projectId: 'metro-1f17c',
    storageBucket: 'metro-1f17c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5zuSXmAYNF0uYmkLPrDPS6ARBmZoQ-Go',
    appId: '1:794337546916:ios:fc02ce54888170be554c31',
    messagingSenderId: '794337546916',
    projectId: 'metro-1f17c',
    storageBucket: 'metro-1f17c.appspot.com',
    iosBundleId: 'com.example.metro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5zuSXmAYNF0uYmkLPrDPS6ARBmZoQ-Go',
    appId: '1:794337546916:ios:fc02ce54888170be554c31',
    messagingSenderId: '794337546916',
    projectId: 'metro-1f17c',
    storageBucket: 'metro-1f17c.appspot.com',
    iosBundleId: 'com.example.metro',
  );
}
